<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DEL1-LHP-N01469" name="test.ui.navision.VerifyDealerItems" tests="1" failures="0" timestamp="3 Jul 2018 07:35:15 GMT" time="34.981" errors="1">
  <testcase name="validateGeneralDetails" time="34.981" classname="test.ui.navision.VerifyDealerItems">
    <error type="java.lang.AssertionError" message="Verification Failed-- expected Item Values and actual Item Values are not same. expected [{DCP=2.31, Description=herlitz Ordner 5450705 A4 PP 50mm weiß , ItemNo=G00779, Stock=88}] but found [{DCP=0.00, Description=Herlitz Quittungen 00886622 A6 2x40Bl, ItemNo=D01274, Stock=410}]">
      <![CDATA[java.lang.AssertionError: Verification Failed-- expected Item Values and actual Item Values are not same. expected [{DCP=2.31, Description=herlitz Ordner 5450705 A4 PP 50mm weiß , ItemNo=G00779, Stock=88}] but found [{DCP=0.00, Description=Herlitz Quittungen 00886622 A6 2x40Bl, ItemNo=D01274, Stock=410}]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at test.ui.navision.VerifyDealerItems.validateGeneralDetails(VerifyDealerItems.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- validateGeneralDetails -->
</testsuite> <!-- test.ui.navision.VerifyDealerItems -->
